### ISSUE TITLE
API文件欄位屬性

### ISSUE THREAD

**Issue by osk2** [comdan66/weather#3]
Hi

感謝提供這麼方便的API

在API文件中有些問題

![screen shot 2017-02-21 at 10 45 59 pm](https://cloud.githubusercontent.com/assets/705280/23169669/a6a5ccb0-f887-11e6-929b-3d4b04c4866f.png)

像是溫濕度，回傳的值全部都是String，但文件是寫Number

追了一下source code，這段應該還要在多做屬性的轉換 😛 
https://github.com/comdan66/weather/blob/master/cmd/libs/Weather.php#L50-L58

**Comment by oawu** [comment]
哈哈哈哈，感謝提醒！！
最近比較沒時間改，有時間後我會補上， >"<
請先把他當字串吧ＸＤ

**Comment by oawu** [comment]
終於找到時間 Fix 囉！
關於 Api 內的 json value type 問題已經 Fix 囉～
